title: Ignacio Manzur
description: Ignacio's website. 
remote_theme: jekyll/minima@v3.0
plugins:
  - jekyll-remote-theme

# This line makes the top navigation include these pages automatically:
header_pages:
  - talks.md
  - cv.md

# Optional (nice social footer links):
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/nachitomanzur" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ignacio-manzur-0220121b7/" }
    - { platform: twitter, user_url: "https://x.com/nachitomanzur" }
