# _config.yml
title: Ignacio Manzur
description: A website.
theme: minima

header_pages:
  - talks.md
  - cv.md

minima:
  author:
    name: Ignacio Manzur
    github: nachitomanzur
    linkedin: ignacio-manzur-0220121b7/
    twitter: nachitomanzur
